import type { Metadata } from 'next'
import { Inter, Rajdhani } from 'next/font/google'
import NavBar from './NavBar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const rajdhani = Rajdhani({
  subsets: ['latin'],
  weight: ['600', '700'],
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={rajdhani.className}>
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  )
}
